version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - revive
    - errcheck
    - ineffassign
    - gosimple
    - unused

issues:
  fix: false
  max-issues-per-linter: 0
  max-same-issues: 0
