# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import authz_pb2 as authz__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in authz_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthorizationServiceStub(object):
    """AuthorizationService provides high-performance authorization checks.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/cedar.v1.AuthorizationService/Check',
                request_serializer=authz__pb2.CheckRequest.SerializeToString,
                response_deserializer=authz__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.BatchCheck = channel.unary_unary(
                '/cedar.v1.AuthorizationService/BatchCheck',
                request_serializer=authz__pb2.BatchCheckRequest.SerializeToString,
                response_deserializer=authz__pb2.BatchCheckResponse.FromString,
                _registered_method=True)
        self.LookupResources = channel.unary_unary(
                '/cedar.v1.AuthorizationService/LookupResources',
                request_serializer=authz__pb2.LookupResourcesRequest.SerializeToString,
                response_deserializer=authz__pb2.LookupResourcesResponse.FromString,
                _registered_method=True)


class AuthorizationServiceServicer(object):
    """AuthorizationService provides high-performance authorization checks.
    """

    def Check(self, request, context):
        """Check performs a single authorization check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchCheck(self, request, context):
        """BatchCheck performs multiple checks in parallel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupResources(self, request, context):
        """LookupResources returns IDs of resources of a given type that the principal can access.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthorizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=authz__pb2.CheckRequest.FromString,
                    response_serializer=authz__pb2.CheckResponse.SerializeToString,
            ),
            'BatchCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchCheck,
                    request_deserializer=authz__pb2.BatchCheckRequest.FromString,
                    response_serializer=authz__pb2.BatchCheckResponse.SerializeToString,
            ),
            'LookupResources': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupResources,
                    request_deserializer=authz__pb2.LookupResourcesRequest.FromString,
                    response_serializer=authz__pb2.LookupResourcesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cedar.v1.AuthorizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cedar.v1.AuthorizationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthorizationService(object):
    """AuthorizationService provides high-performance authorization checks.
    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cedar.v1.AuthorizationService/Check',
            authz__pb2.CheckRequest.SerializeToString,
            authz__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cedar.v1.AuthorizationService/BatchCheck',
            authz__pb2.BatchCheckRequest.SerializeToString,
            authz__pb2.BatchCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cedar.v1.AuthorizationService/LookupResources',
            authz__pb2.LookupResourcesRequest.SerializeToString,
            authz__pb2.LookupResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
